### PR TITLE
Insertion Sort

### PR DESCRIPTION
**Pull request by AkashDeepPatel**
Insertion Sort

### CODE REVIEW

**Comment by rahulbollisetty** [comment]
@all_contributors please add @AkashDeepPatel for <code>

**Comment by rahulbollisetty** [comment]
hi there , if are trying to take 2 pr , you should have submitted after one gets accepted, the way you did is merging those two files. No problem , you may add another algo and make a pr. Though i merged this one.

**Comment by rahulbollisetty** [comment]
@all-contributors please add @AkashDeepPatel  for doc

**Comment by AkashDeepPatel** [comment]
Thank you so much! ☺️

**Pull request merged**
