### PR TITLE
Create KaprekarNumber.java

### PR DESCRIPTION
**Pull request by anneCoder1805**
Code to determine if a number entered by the user is a Kaprekar Number or not.
To check if an n-digit number k is a Kaprekar number or not square it and add the right n digits to the left n or n-1 digits. If the resultant sum is k, then k is called a Kaprekar number. For example, 9 is a Kaprekar number since 9^2 = 81 & 8 + 1 = 9 ; 297 is a Kaprekar number as 297^2 = 88209 & 88 + 209 = 297.

### CODE REVIEW

**Comment by rahulbollisetty** [comment]
> Code to determine if a number enetred by the user is a Kaprekar Number or not.
> To check if an n-digit number k is a Kaprekar number or not square it and add the right n digits to the left n or n-1 digits. If the resultant sum is k, then k is called a Kaprekar number. For example, 9 is a Kaprekar number since 9^2 = 81 & 8 + 1 = 9 ; 297 is a Kaprekar number as 297^2 = 88209 & 88 + 209 = 297.

Hi there, it would be awesome if you created a seperate folder for this , and add a readme.md so this people can understand this and into that folder add this java file.

**Comment by anneCoder1805** [comment]
Sure, I will do it :)

**Comment by rahulbollisetty** [comment]
@all-contributors please add @anneCoder1805 for code

**Comment by rahulbollisetty** [comment]
That's really cool

**Pull request merged**
